# Generated by Django 5.0.1 on 2024-02-18 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('img', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.marca')),
            ],
        ),
        migrations.CreateModel(
            name='arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.marca')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.publicacao')),
            ],
        ),
    ]
