# Generated by Django 5.0.1 on 2024-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criada', models.DateTimeField(auto_now_add=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('views_total', models.IntegerField(default=0)),
            ],
        ),
    ]
