# Generated by Django 5.0.1 on 2024-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_publicacao_tag_alter_relgaleria_data_atualizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
