# Generated by Django 5.0.1 on 2024-02-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_marca_cor_1_marca_cor_2_marca_cor_3_marca_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
